name: Deploy
on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: pnpm build-keycloak-theme
  create_release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: extract tag
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
      - uses: reedyuk/npm-version@1.2.2
        with:
          git-tag-version: false
          version: ${{ steps.extract_tag.outputs.tag }}
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: pnpm build-keycloak-theme
      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.extract_tag.outputs.tag }}
          tag_name: ${{ steps.extract_tag.output.tag }}
          generate_release_notes: true
          draft: false
          files: dist_keycloak/keycloak-theme-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
