name: Release Drafter
on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  ref: ${{ github.event.pull_request.head.sha }} # to check out the actual pull request commit, not the merge commit
                  fetch-depth: 0 # a full history is required for pull request analysis
            - name: "Qodana Scan"
              uses: JetBrains/qodana-action@v2024.2
              with:
                  pr-mode: false
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2131535892 }}
                  QODANA_ENDPOINT: "https://qodana.cloud"
    update_release_draft:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: release-drafter/release-drafter@v6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
